(ocamllex irj_lexer)

(menhir
 (modules irj_parser)
 (flags --dump --explain --table))

(library
 (name irj_utils)
 (public_name mlang.irj_utils)
 (flags
  (:standard -open Utils -open M_ir))
 (libraries m_frontend m_ir m_interpreter utils menhirLib parmap str
   mlang.messages))

; Generates the Parser_messages module

(rule
 (target parserMessages.ml)
 (deps
  (:parser irj_parser.mly)
  (:msg parserMessages.messages))
 (action
  (with-stdout-to
   %{target}
   (run menhir %{parser} --base %{parser} --compile-errors %{msg}))))

; Rules to check parser updates and properly merging the changes

(rule
 (target new.messages)
 (deps
  (:parser irj_parser.mly))
 (action
  (with-stdout-to
   %{target}
   (run menhir %{parser} --base %{parser} --list-errors))))

(rule
 (target updated.messages)
 (deps
  (:parser irj_parser.mly)
  (:msg parserMessages.messages))
 (action
  (with-stdout-to
   %{target}
   (run menhir %{parser} --base %{parser} --update-errors %{msg}))))

(rule
 (target parserMessages.messages.updated)
 (deps
  (:parser irj_parser.mly)
  (:new new.messages)
  (:updated updated.messages))
 (action
  (with-stdout-to
   %{target}
   (run menhir %{parser} --base %{parser} --merge-errors %{new}
     --merge-errors %{updated}))))

; Tests the parserMessages.messages file when the parser changes.
; To update the file, use dune runtest --auto-update

(rule
 (alias runtest)
 (package mlang)
 (deps parserMessages.messages parserMessages.messages.updated)
 (action
  (diff parserMessages.messages parserMessages.messages.updated)))
