(******************************************************************************)
(*                                                                            *)
(* Droit d'auteur (c) 2026 DGFiP - INRIA                                      *)
(*                                                                            *)
(* Ce programme est distribué sous la licence CeCILL-C: vous pouvez le        *)
(* redistribuer et/ou le modifier sous les contraintes de celle-ci.           *)
(*                                                                            *)
(* L'accessibilité au code source et les droits de copie, de modification et  *)
(* de redistribution qui découlent de ce contrat ont pour contrepartie de     *)
(* n'offrir aux utilisateurs qu'une garantie limitée et de ne faire peser sur *)
(* l'auteur du logiciel, le titulaire des droits patrimoniaux et les          *)
(* concédants successifs qu'une responsabilité restreinte.                    *)
(*                                                                            *)
(******************************************************************************)

type id_scope = { sid : string; mutable used_scope : bool }

type scope =
  | Id of id_scope (* The identifier of a given scope *)
  | Sanitize of { san_id : int; san : unit -> unit }
(* Some code blocks require to be properly cleaned before being stopped.
   For example, when a stop happens in a restoration inside an iteration,
   we must properly sanitize the restoration before jumping to the
   end of the loop. *)

(* An environment to keep track of local ids' scopes through the
   compilation. Local labels are used to specify the locations targetted by
   gotos generated by the 'stop;' instructions. *)
type env = {
  dgfip_flags : Dgfip_options.flags;
  prog : Mir.program;
  mutable scopes : scope list;
  (* Each M iterator will be given a specific id, which will be used as a
     C local label. The head of the list corresponds to the id of the
     current scope, while its tail contails the scopes the current one
     belong to. *)
  quit_label : string;
  (* The label name used for quitting completely the current target. *)
  mutable uses_quit_label : bool;
  mutable uses_curr_varspace : bool;
  mutable uses_saisie_def : bool;
  mutable uses_calculee_def : bool;
  mutable uses_base_def : bool;
  mutable uses_saisie_val : bool;
  mutable uses_calculee_val : bool;
  mutable uses_base_val : bool;
}
